---
apiVersion: v1
kind: Namespace
metadata:
  name: bluebook
  labels:
    team: bluebook
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  namespace: bluebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: httpd
        image: registry.access.redhat.com/ubi8/httpd-24:latest
        ports:
        - containerPort: 8080
